(function(){
'use strict';

var workspaceState={settings:{defaultFolders:[]},projects:[],current:null};
var designToolState={items:[]};
function dataOf(value){return value&&value.data!==undefined?value.data:value;}
function studioState(id,text,kind){var el=document.getElementById(id);if(!el)return;el.textContent=text||'';el.className='studio-state '+(kind||'');}

async function loadEngineeringWorkspace(preferredId){
  try{
    var snapshot=dataOf(await api('v1/workspace'));
    workspaceState.settings=snapshot.settings||{defaultFolders:[]}; workspaceState.projects=snapshot.projects||[];
    var select=document.getElementById('projectSelect');
    if(select){select.innerHTML='<option value="">选择已有项目…</option>'+workspaceState.projects.map(function(p){return '<option value="'+attr(p.id)+'">'+esc(p.name)+'</option>';}).join('');}
    var id=preferredId||(workspaceState.current&&workspaceState.current.id)||(select&&select.value)||'';
    if(!id&&workspaceState.projects.length) id=workspaceState.projects[0].id;
    if(select) select.value=id;
    var folders=document.getElementById('projectFolderTemplates');if(folders)folders.value=(workspaceState.settings.defaultFolders||[]).join('\n');
    if(id) await openEngineeringProject(id); else renderEngineeringProject(null);
  }catch(error){studioState('projectCreateState','读取工程工作区失败：'+error.message,'bad');}
}

async function openEngineeringProject(id){
  if(!id){workspaceState.current=null;renderEngineeringProject(null);return;}
  try{workspaceState.current=dataOf(await api('v1/projects/'+encodeURIComponent(id)));renderEngineeringProject(workspaceState.current);}
  catch(error){studioState('projectCreateState','读取项目失败：'+error.message,'bad');}
}

function renderEngineeringProject(project){
  var empty=document.getElementById('projectEmpty'),content=document.getElementById('projectContent');
  if(empty)empty.style.display=project?'none':'block';if(content)content.style.display=project?'block':'none';
  if(!project)return;
  var title=document.getElementById('activeProjectTitle');if(title)title.textContent=project.name;
  var pathEl=document.getElementById('activeProjectPath');if(pathEl)pathEl.textContent=project.projectDirectory;
  var progress=project.checklistProgress||{ready:0,applicable:0,total:0,percent:0};
  var missing=Math.max(0,Number(progress.applicable||0)-Number(progress.ready||0));
  var metrics=document.getElementById('projectMetrics');if(metrics)metrics.innerHTML='<div class="metric-card"><strong>'+Number(project.folders.length||0)+'</strong><span>项目目录</span></div><div class="metric-card"><strong>'+Number(progress.percent||0)+'%</strong><span>资料完整率</span></div><div class="metric-card"><strong>'+missing+'</strong><span>待完善事项</span></div>';
  var folderList=document.getElementById('projectFolderList');if(folderList)folderList.innerHTML=(project.folders||[]).map(function(folder){return '<span class="folder-chip">'+esc(folder)+'</span>';}).join('');
  var bar=document.getElementById('checklistProgress');if(bar)bar.style.width=Number(progress.percent||0)+'%';
  var count=document.getElementById('checklistCount');if(count)count.textContent=progress.ready+' / '+progress.applicable+' 已具备';
  renderChecklist(project.checklist||[]);
}

function renderChecklist(items){
  var groups={};items.forEach(function(item){(groups[item.category]||(groups[item.category]=[])).push(item);});
  var list=document.getElementById('checklistList');if(!list)return;
  list.innerHTML=Object.keys(groups).map(function(category){return '<section class="check-group"><h4>'+esc(category)+'</h4>'+groups[category].map(function(item){return '<div class="check-item '+attr(item.status)+'" data-check-item="'+attr(item.id)+'"><select data-check-status="'+attr(item.id)+'"><option value="missing" '+(item.status==='missing'?'selected':'')+'>待收集</option><option value="ready" '+(item.status==='ready'?'selected':'')+'>已具备</option><option value="na" '+(item.status==='na'?'selected':'')+'>不适用</option></select><div class="check-label">'+esc(item.label)+'</div><input data-check-note="'+attr(item.id)+'" value="'+attr(item.note||'')+'" placeholder="备注、资料位置或责任人"></div>';}).join('')+'</section>';}).join('');
}

async function createEngineeringProject(){
  var name=document.getElementById('projectName').value.trim(),baseDirectory=document.getElementById('projectBase').value.trim();
  if(!name||!baseDirectory){studioState('projectCreateState','请填写项目名称并选择保存目录。','bad');return;}
  studioState('projectCreateState','正在创建标准项目目录…','');
  try{
    var created=dataOf(await api('v1/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:name,baseDirectory:baseDirectory})}));
    studioState('projectCreateState','项目目录已创建：'+created.projectDirectory,'ok');
    await loadEngineeringWorkspace(created.id);
  }catch(error){studioState('projectCreateState','创建失败：'+error.message,'bad');}
}

async function chooseProjectBase(){if(!DESKTOP||!DESKTOP.dialog.chooseProjectDirectory)return;var value=await DESKTOP.dialog.chooseProjectDirectory();if(value)document.getElementById('projectBase').value=value;}
async function updateChecklist(itemId,patch){if(!workspaceState.current)return;try{workspaceState.current=dataOf(await api('v1/projects/'+encodeURIComponent(workspaceState.current.id)+'/checklist/'+encodeURIComponent(itemId),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(patch)}));renderEngineeringProject(workspaceState.current);}catch(error){studioState('projectCreateState','检查项保存失败：'+error.message,'bad');}}
async function addChecklistItem(){if(!workspaceState.current)return;var category=document.getElementById('customCheckCategory').value.trim(),label=document.getElementById('customCheckLabel').value.trim();if(!label)return;try{workspaceState.current=dataOf(await api('v1/projects/'+encodeURIComponent(workspaceState.current.id)+'/checklist',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({category:category,label:label})}));document.getElementById('customCheckLabel').value='';renderEngineeringProject(workspaceState.current);}catch(error){studioState('projectCreateState','添加失败：'+error.message,'bad');}}
async function syncProjectFolders(){if(!workspaceState.current)return;try{workspaceState.current=dataOf(await api('v1/projects/'+encodeURIComponent(workspaceState.current.id)+'/folders/sync',{method:'POST'}));renderEngineeringProject(workspaceState.current);studioState('projectCreateState','目录模板已同步到当前项目。','ok');}catch(error){studioState('projectCreateState','同步失败：'+error.message,'bad');}}
async function saveWorkspaceSettings(){var values=document.getElementById('projectFolderTemplates').value.split(/\r?\n/).map(function(x){return x.trim();}).filter(Boolean);try{workspaceState.settings=dataOf(await api('v1/workspace',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({defaultFolders:values})}));studioState('workspaceSettingsState','目录模板已保存，新建项目时生效。','ok');}catch(error){studioState('workspaceSettingsState','保存失败：'+error.message,'bad');}}

async function refreshBalance(){
  var button=document.getElementById('balanceTitleButton'),label=document.getElementById('balanceTitleLabel');if(!button||!label||!DESKTOP||!DESKTOP.balance)return;
  button.classList.add('loading');label.textContent='余额 …';
  try{var result=await DESKTOP.balance.get();button.classList.toggle('ok',!!result.ok);button.classList.toggle('warn',!result.ok);if(result.ok){var info=(result.balanceInfos||[]).find(function(x){return x.currency==='CNY';})||(result.balanceInfos||[])[0];label.textContent=(info&&info.currency==='CNY'?'¥ ':'')+(info?info.total_balance:'0.00');button.title='DeepSeek API 余额，点击刷新';}else{label.textContent=result.configured?'查询失败':'余额未配置';button.title=result.message||'点击刷新';}}
  catch(error){label.textContent='查询失败';button.classList.add('warn');button.title=error.message;}finally{button.classList.remove('loading');}
}

async function loadDesignTools(){if(!DESKTOP||!DESKTOP.designTools)return;try{designToolState=await DESKTOP.designTools.list();var calc=(designToolState.items||[]).find(function(x){return x.id==='calculator';});var pathInput=document.getElementById('calculatorPath');if(pathInput&&calc)pathInput.value=calc.path||'';var state=document.getElementById('calculatorState');if(state&&calc){state.textContent=calc.available?'可用：'+calc.path:'未找到程序，请重新选择';state.className='studio-state '+(calc.available?'ok':'bad');}var badge=document.getElementById('calculatorBadge');if(badge)badge.textContent=calc&&calc.available?'可用':'未配置';}catch(error){studioState('calculatorState','读取设计工具失败：'+error.message,'bad');}}
async function chooseCalculator(){if(!DESKTOP||!DESKTOP.dialog.chooseDesignTool)return;var value=await DESKTOP.dialog.chooseDesignTool();if(value)document.getElementById('calculatorPath').value=value;}
async function saveCalculator(){if(!DESKTOP||!DESKTOP.designTools)return;try{await DESKTOP.designTools.update('calculator',{path:document.getElementById('calculatorPath').value});await loadDesignTools();}catch(error){studioState('calculatorState','保存失败：'+error.message,'bad');}}
async function launchCalculator(){if(!DESKTOP||!DESKTOP.designTools){studioState('toolLaunchState','仅桌面版支持启动本地程序。','bad');return;}try{await DESKTOP.designTools.launch('calculator');studioState('toolLaunchState','多功能计算器已启动。','ok');}catch(error){studioState('toolLaunchState',error.message,'bad');}}

var specMonitorState={items:[],editing:''};
function monitorStatusLabel(status){return{pending:'待建立基线',baseline:'基线已建立',unchanged:'未发现变化',changed:'发现更新',error:'检查失败'}[status]||status||'待检查';}
function monitorTime(value){if(!value)return'尚未检查';try{return new Date(value).toLocaleString();}catch(_){return value;}}
async function loadSpecMonitors(){try{var value=dataOf(await api('v1/spec-monitors'));specMonitorState.items=value.items||[];renderSpecMonitors();}catch(error){var summary=document.getElementById('specMonitorSummary');if(summary)summary.textContent='读取监测任务失败：'+error.message;}}
function renderSpecMonitors(){
  var items=specMonitorState.items||[],changed=items.filter(function(item){return item.status==='changed';}).length,errors=items.filter(function(item){return item.status==='error';}).length;
  var badge=document.getElementById('specMonitorBadge');if(badge)badge.textContent=items.length+' 个网站';
  var summary=document.getElementById('specMonitorSummary');if(summary)summary.textContent=changed?changed+' 个网站发现规范变化':errors?errors+' 个网站检查失败':'定时检查指定网站上的规范发布与更新。';
  var count=document.getElementById('specMonitorCount');if(count)count.textContent='· '+items.length+' 项';
  var list=document.getElementById('specMonitorList');if(!list)return;
  if(!items.length){list.innerHTML='<div class="spec-monitor-empty">尚未添加监测网站。<br>在左侧填写公开规范发布页即可建立更新基线。</div>';return;}
  list.innerHTML=items.map(function(item){var changes=item.lastChanges||{added:[],removed:[]},links=(changes.added||[]).map(function(link){return'<a href="'+attr(link.url)+'" target="_blank" rel="noopener">＋ '+esc(link.title)+'</a>';}).join(''),removed=(changes.removed||[]).map(function(link){return'<div>－ '+esc(link.title)+'</div>';}).join('');return'<article class="spec-monitor-item '+attr(item.status)+'"><div class="monitor-item-head"><div class="monitor-item-copy"><strong>'+esc(item.name)+'</strong><a class="monitor-item-url" href="'+attr(item.url)+'" target="_blank" rel="noopener">'+esc(item.url)+'</a></div><span class="monitor-status '+attr(item.status)+'">'+esc(monitorStatusLabel(item.status))+'</span></div><div class="monitor-meta"><span>周期 '+Math.round(Number(item.intervalMinutes||0)/60*10)/10+' 小时</span><span>上次 '+esc(monitorTime(item.lastCheckedAt))+'</span><span>识别 '+Number((item.entries||[]).length)+' 条</span><span>'+(item.enabled?'自动检查已开启':'已暂停')+'</span></div>'+(item.lastError?'<div class="monitor-error">'+esc(item.lastError)+'</div>':'')+((links||removed)?'<div class="monitor-change-list">'+links+removed+'</div>':'')+'<div class="monitor-actions"><button class="btn" data-studio-act="checkSpecMonitor" data-monitor-id="'+attr(item.id)+'">立即检查</button><button class="btn" data-studio-act="editSpecMonitor" data-monitor-id="'+attr(item.id)+'">编辑</button><button class="btn" data-studio-act="toggleSpecMonitor" data-monitor-id="'+attr(item.id)+'">'+(item.enabled?'暂停':'启用')+'</button><button class="btn btn-danger" data-studio-act="deleteSpecMonitor" data-monitor-id="'+attr(item.id)+'">删除</button></div></article>';}).join('');
}
function openSpecMonitors(){var dialog=document.getElementById('specMonitorDialog');dialog.style.display='flex';dialog.setAttribute('aria-hidden','false');loadSpecMonitors();}
function closeSpecMonitors(){var dialog=document.getElementById('specMonitorDialog');dialog.style.display='none';dialog.setAttribute('aria-hidden','true');}
function resetSpecMonitorForm(){specMonitorState.editing='';document.getElementById('specMonitorId').value='';document.getElementById('specMonitorName').value='';document.getElementById('specMonitorUrl').value='';document.getElementById('specMonitorInterval').value='1440';document.getElementById('specMonitorKeywords').value='';studioState('specMonitorFormState','','');}
function editSpecMonitor(id){var item=specMonitorState.items.find(function(entry){return entry.id===id;});if(!item)return;specMonitorState.editing=id;document.getElementById('specMonitorId').value=id;document.getElementById('specMonitorName').value=item.name||'';document.getElementById('specMonitorUrl').value=item.url||'';document.getElementById('specMonitorInterval').value=String(item.intervalMinutes||1440);document.getElementById('specMonitorKeywords').value=(item.keywords||[]).join(', ');studioState('specMonitorFormState','正在编辑“'+item.name+'”','');}
async function saveSpecMonitor(){var id=specMonitorState.editing,payload={name:document.getElementById('specMonitorName').value.trim(),url:document.getElementById('specMonitorUrl').value.trim(),intervalMinutes:Number(document.getElementById('specMonitorInterval').value),keywords:document.getElementById('specMonitorKeywords').value.trim()};if(!payload.name||!payload.url){studioState('specMonitorFormState','请填写监测名称和网站地址。','bad');return;}studioState('specMonitorFormState',id?'正在保存…':'正在建立网站基线…','');try{if(id){await api('v1/spec-monitors/'+encodeURIComponent(id),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});await api('v1/spec-monitors/'+encodeURIComponent(id)+'/check',{method:'POST'});}else await api('v1/spec-monitors',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});resetSpecMonitorForm();await loadSpecMonitors();}catch(error){studioState('specMonitorFormState','保存失败：'+error.message,'bad');}}
async function checkSpecMonitor(id){studioState('specMonitorFormState','正在检查网站…','');try{await api('v1/spec-monitors/'+encodeURIComponent(id)+'/check',{method:'POST'});await loadSpecMonitors();studioState('specMonitorFormState','检查完成。','ok');}catch(error){studioState('specMonitorFormState','检查失败：'+error.message,'bad');}}
async function checkAllSpecMonitors(){studioState('specMonitorFormState','正在检查所有启用的网站…','');try{await api('v1/spec-monitors/check-all',{method:'POST'});await loadSpecMonitors();studioState('specMonitorFormState','全部检查完成。','ok');}catch(error){studioState('specMonitorFormState','检查失败：'+error.message,'bad');}}
async function toggleSpecMonitor(id){var item=specMonitorState.items.find(function(entry){return entry.id===id;});if(!item)return;try{await api('v1/spec-monitors/'+encodeURIComponent(id),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({enabled:!item.enabled})});await loadSpecMonitors();studioState('specMonitorFormState',item.enabled?'监测已暂停。':'监测已启用。','ok');}catch(error){studioState('specMonitorFormState','操作失败：'+error.message,'bad');}}
async function deleteSpecMonitor(id){var item=specMonitorState.items.find(function(entry){return entry.id===id;});if(!item||!window.confirm('删除规范监测任务“'+item.name+'”？历史检查记录也会删除。'))return;try{await api('v1/spec-monitors/'+encodeURIComponent(id),{method:'DELETE'});if(specMonitorState.editing===id)resetSpecMonitorForm();await loadSpecMonitors();studioState('specMonitorFormState','监测任务已删除。','ok');}catch(error){studioState('specMonitorFormState','删除失败：'+error.message,'bad');}}

var slope={nodes:[],edges:[],mode:'select',selected:{type:'nodes',ids:[]},drag:null,selectionBox:null,serial:1,edgeSerial:1,direction:'right',lastResults:null};
function slopeDecimals(){return Math.max(0,Math.min(6,Number(document.getElementById('slopeDecimals')?.value)||3));}
function slopePoint(event){var svg=document.getElementById('slopeCanvas'),rect=svg.getBoundingClientRect();return{x:Math.round((event.clientX-rect.left)*1000/rect.width/5)*5,y:Math.round((event.clientY-rect.top)*600/rect.height/5)*5};}
function slopeNode(key){return slope.nodes.find(function(node){return node.key===key;});}
function slopeEdge(id){return slope.edges.find(function(edge){return edge.id===id;});}
function slopeLabel(key){var node=slopeNode(key);return node?node.label:key;}
function selectedNodeKeys(){return slope.selected&&slope.selected.type==='nodes'?slope.selected.ids||[]:[];}
function saveSlope(){try{localStorage.setItem('specflow-road-slope',JSON.stringify({schemaVersion:3,nodes:slope.nodes,edges:slope.edges,serial:slope.serial,edgeSerial:slope.edgeSerial,direction:slope.direction}));}catch(_){}}
function defaultEdge(){return{distance:Number(document.getElementById('slopeDistanceDefault')?.value)||20,slope:Number(document.getElementById('slopeDefault')?.value)||5,minSlope:Number(document.getElementById('slopeMinDefault')?.value)||0,maxSlope:''};}
function normalizeSlopeSegments(){if(!window.SpecFlowRoadSlope||!window.SpecFlowRoadSlope.normalizeSegments)return{edges:slope.edges,splitEdges:0,clearedDistances:0,duplicates:0};var result=window.SpecFlowRoadSlope.normalizeSegments({nodes:slope.nodes,edges:slope.edges,tolerance:30});slope.edges=result.edges;if(slope.selected&&slope.selected.type==='edge'&&!slopeEdge(slope.selected.id))slope.selected={type:'nodes',ids:[]};return result;}
function reportSlopeNormalization(result){if(result&&result.splitEdges)studioState('slopeState','已把 '+result.splitEdges+' 条跨节点坡段拆成逐节点连线；请重新填写标记为“待填”的各段实际距离。','bad');}
function migrateSlope(data){var nodes=(data.nodes||[]).map(function(node,index){return{key:String(node.key||node.id||('N'+(index+1))),label:String(node.label||node.id||('P'+(index+1))),x:Number(node.x)||100+index*100,y:Number(node.y)||100,elevation:node.elevation==null?null:Number(node.elevation),fixed:Boolean(node.fixed)};}),known=new Set(nodes.map(function(node){return node.key;})),edgeDefaults=defaultEdge(),edges=(data.edges||[]).filter(function(edge){return known.has(String(edge.from))&&known.has(String(edge.to));}).map(function(edge,index){return{id:String(edge.id||('E'+(index+1))),from:String(edge.from),to:String(edge.to),distance:edge.distance===''?'':Number(edge.distance)>0?Number(edge.distance):edgeDefaults.distance,slope:Number.isFinite(Number(edge.slope))?Number(edge.slope):edgeDefaults.slope,minSlope:edge.minSlope===''?'':Number.isFinite(Number(edge.minSlope))?Number(edge.minSlope):edgeDefaults.minSlope,maxSlope:edge.maxSlope===''?'':Number.isFinite(Number(edge.maxSlope))?Number(edge.maxSlope):'',needsDistance:Boolean(edge.needsDistance)};});var normalized=window.SpecFlowRoadSlope&&window.SpecFlowRoadSlope.normalizeSegments?window.SpecFlowRoadSlope.normalizeSegments({nodes:nodes,edges:edges,tolerance:30}):{edges:edges,splitEdges:0,clearedDistances:0,duplicates:0};return{nodes:nodes,edges:normalized.edges,serial:Number(data.serial)||nodes.length+1,edgeSerial:Number(data.edgeSerial)||edges.length+1,direction:data.direction||'right',normalization:normalized};}
function loadSlope(){try{var data=migrateSlope(JSON.parse(localStorage.getItem('specflow-road-slope')||'{}'));slope.nodes=data.nodes;slope.edges=data.edges;slope.serial=data.serial;slope.edgeSerial=data.edgeSerial;slope.direction=data.direction;slope.normalization=data.normalization;}catch(_){}setSlopeDirection(slope.direction);renderSlope();reportSlopeNormalization(slope.normalization);}
function setSlopeMode(mode){slope.mode=mode;document.querySelectorAll('[data-slope-mode]').forEach(function(button){button.classList.toggle('active',button.getAttribute('data-slope-mode')===mode);});renderSlope();}
function setSlopeDirection(direction){slope.direction=['up','right','down','left'].includes(direction)?direction:'right';document.querySelectorAll('[data-direction]').forEach(function(button){button.classList.toggle('active',button.getAttribute('data-direction')===slope.direction);});saveSlope();}
function slopeLine(edge){var a=slopeNode(edge.from),b=slopeNode(edge.to);if(!a||!b)return null;var dx=b.x-a.x,dy=b.y-a.y,length=Math.max(1,Math.hypot(dx,dy)),ux=dx/length,uy=dy/length,offset=Math.min(38,length/3);return{x1:a.x+ux*offset,y1:a.y+uy*offset,x2:b.x-ux*offset,y2:b.y-uy*offset,mx:(a.x+b.x)/2,my:(a.y+b.y)/2-13,ux:ux,uy:uy,cx:(a.x+b.x)/2,cy:(a.y+b.y)/2};}
function renderSlope(){
  var svg=document.getElementById('slopeCanvas');if(!svg)return;var decimals=slopeDecimals(),selectedKeys=new Set(selectedNodeKeys());
  var markup='<defs><pattern id="roadGrid" width="25" height="25" patternUnits="userSpaceOnUse"><path d="M25 0H0V25" fill="none" stroke="#252b35" stroke-width="1"/></pattern><marker id="slopeArrow" markerWidth="9" markerHeight="9" refX="8" refY="4.5" orient="auto"><path d="M0 0 9 4.5 0 9Z" fill="#7aa2ff"/></marker></defs><rect width="1000" height="600" fill="url(#roadGrid)"/>';
  markup+=slope.edges.map(function(edge,index){var line=slopeLine(edge);if(!line)return'';var selected=slope.selected&&slope.selected.type==='edge'&&slope.selected.id===edge.id,label=edge.distance===''?'待填距离 · '+Number(edge.slope||0).toFixed(2)+'‰':Number(edge.distance||0).toFixed(1)+'m · '+Number(edge.slope||0).toFixed(2)+'‰';return'<g class="road-edge '+(selected?'selected':'')+'" data-slope-edge="'+attr(edge.id)+'"><line class="road-edge-base" x1="'+line.x1+'" y1="'+line.y1+'" x2="'+line.x2+'" y2="'+line.y2+'"/><line class="road-edge-arrow" x1="'+line.x1+'" y1="'+line.y1+'" x2="'+line.x2+'" y2="'+line.y2+'" marker-end="url(#slopeArrow)"/><circle class="road-flow-dot" r="4"><animateMotion dur="1.35s" begin="-'+((index%4)*0.23).toFixed(2)+'s" repeatCount="indefinite" path="M '+line.x1+' '+line.y1+' L '+line.x2+' '+line.y2+'"/></circle><text x="'+line.mx+'" y="'+line.my+'">'+esc(label)+'</text></g>';}).join('');
  markup+=slope.nodes.map(function(node){var selected=selectedKeys.has(node.key),elevation=node.elevation==null?'未定':Number(node.elevation).toFixed(decimals)+' m';return'<g class="road-node '+(node.fixed?'fixed ':'')+(selected?'selected ':'')+'" data-slope-node="'+attr(node.key)+'" transform="translate('+node.x+' '+node.y+')"><rect x="-38" y="-21" width="76" height="42" rx="9"/><text y="-2">'+esc(node.label)+'</text><text class="road-elevation" y="13">'+esc(elevation)+'</text></g>';}).join('');
  if(slope.selectionBox){var box=slope.selectionBox,x=Math.min(box.start.x,box.current.x),y=Math.min(box.start.y,box.current.y),w=Math.abs(box.current.x-box.start.x),h=Math.abs(box.current.y-box.start.y);markup+='<rect class="road-selection" x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'"/>';}
  if(!slope.nodes.length)markup+='<text class="road-empty" x="500" y="285">选择“连续插入节点”，在画布中单击</text><text class="road-empty-sub" x="500" y="310">后续节点会逐段连接；双击节点也可按工具栏方向延伸</text>';
  svg.innerHTML=markup;renderSlopeInspector();renderSlopeResults();saveSlope();
}
function renderSlopeInspector(){var box=document.getElementById('slopeInspectorContent');if(!box)return;var selected=slope.selected;if(!selected||(selected.type==='nodes'&&!selected.ids.length)){box.innerHTML='<div class="road-help">框选可一次选择多个节点并整体移动。节点坐标只控制示意布局；网络计算只使用坡段中输入的实际距离、排水方向、设计坡度和规范限值。</div>';return;}if(selected.type==='nodes'){if(selected.ids.length>1){box.innerHTML='<div class="road-help">已选择 '+selected.ids.length+' 个节点。按选择顺序可连接前两个节点；任何中间节点都会自动拆成独立坡段。</div><button class="btn" style="margin-top:9px" data-studio-act="connectSlopeNodes">连接前两个节点</button>';return;}var node=slopeNode(selected.ids[0]);if(!node)return;var incident=slope.edges.filter(function(edge){return edge.from===node.key||edge.to===node.key;}).length;box.innerHTML='<div class="studio-field"><label>节点编号</label><input data-slope-prop="nodeLabel" value="'+attr(node.label)+'"></div><div class="studio-field"><label>已知设计标高（m）</label><input type="number" step="0.001" data-slope-prop="elevation" value="'+(node.elevation==null?'':node.elevation)+'" placeholder="未知时留空"></div><label class="switch"><input type="checkbox" data-slope-prop="fixed" '+(node.fixed?'checked':'')+'><span>设为已知控制标高</span></label>'+(incident?'<div class="road-node-actions"><button class="btn" data-studio-act="slopeNodeHigh">设为分水高点</button><button class="btn" data-studio-act="slopeNodeLow">设为汇水低点</button></div>':'')+'<div class="road-help" style="margin-top:9px">“分水高点”会让相邻箭头全部向外；“汇水低点”会让相邻箭头全部指向此节点。双击节点仍可逐段延伸。</div>';return;}var edge=slopeEdge(selected.id);if(!edge)return;box.innerHTML='<div class="studio-field"><label>排水方向</label><input value="'+attr(slopeLabel(edge.from)+' → '+slopeLabel(edge.to))+'" disabled></div><div class="road-inspector-grid"><div class="studio-field"><label>实际距离（m）</label><input type="number" min="0.01" step="0.1" data-slope-prop="edgeDistance" value="'+attr(edge.distance)+'" placeholder="必须填写"></div><div class="studio-field"><label>设计坡度（‰）</label><input type="number" step="0.1" data-slope-prop="edgeSlope" value="'+attr(edge.slope)+'"></div><div class="studio-field"><label>规范最小坡度（‰）</label><input type="number" min="0" step="0.1" data-slope-prop="edgeMinSlope" value="'+attr(edge.minSlope)+'"></div><div class="studio-field"><label>规范最大坡度（‰）</label><input type="number" min="0" step="0.1" data-slope-prop="edgeMaxSlope" value="'+attr(edge.maxSlope)+'" placeholder="可留空"></div></div><button class="btn" data-studio-act="reverseSlopeEdge">反向排水</button><div class="road-help" style="margin-top:9px">水流动画只在本坡段的两个端点之间运行，不会越过中间节点。</div>';}
function renderSlopeResults(){var table=document.getElementById('slopeResults');if(!table)return;var results=slope.lastResults&&slope.lastResults.edgeResults||[];table.innerHTML='<thead><tr><th>坡段</th><th>实距</th><th>计算坡度</th><th>状态</th></tr></thead><tbody>'+slope.edges.map(function(edge){var result=results.find(function(item){return item.id===edge.id;}),status=result?result.status:'pending',actual=result&&result.actualSlope!=null?result.actualSlope.toFixed(2)+'‰':'—',message=result&&result.issues.length?result.issues.join('；'):'通过',distance=edge.distance===''?'待填':Number(edge.distance||0).toFixed(2)+'m';return'<tr class="'+attr(status)+'" title="'+attr(message)+'"><td>'+esc(slopeLabel(edge.from)+'→'+slopeLabel(edge.to))+'</td><td>'+esc(distance)+'</td><td>'+actual+'</td><td>'+esc(status==='ok'?'通过':status==='pending'?'待计算':message)+'</td></tr>';}).join('')+'</tbody>';}
function createSlopeNode(point,label){var number=slope.serial++,key='N'+Date.now().toString(36)+'_'+number,node={key:key,label:label||('P'+number),x:Math.max(50,Math.min(950,point.x)),y:Math.max(35,Math.min(565,point.y)),elevation:null,fixed:false};slope.nodes.push(node);slope.selected={type:'nodes',ids:[key]};slope.lastResults=null;return node;}
function slopePairKey(from,to){return[from,to].sort().join('\n');}
function createSlopeEdge(from,to){if(!from||!to||from===to)return[];var defaults=defaultEdge(),keys=window.SpecFlowRoadSlope&&window.SpecFlowRoadSlope.segmentNodeKeys?window.SpecFlowRoadSlope.segmentNodeKeys(from,to,slope.nodes,30):[from,to],created=[];for(var index=0;index<keys.length-1;index+=1){var segmentFrom=keys[index],segmentTo=keys[index+1],pair=slopePairKey(segmentFrom,segmentTo),existing=slope.edges.find(function(edge){return slopePairKey(edge.from,edge.to)===pair;});if(existing)continue;var id;do{id='E'+slope.edgeSerial++;}while(slopeEdge(id));var edge={id:id,from:segmentFrom,to:segmentTo,distance:defaults.distance,slope:defaults.slope,minSlope:defaults.minSlope,maxSlope:defaults.maxSlope,needsDistance:false};slope.edges.push(edge);created.push(edge);}slope.lastResults=null;return created;}
function addSlopeNode(point){var previous=selectedNodeKeys().length===1?selectedNodeKeys()[0]:null,target=createSlopeNode(point);if(previous)createSlopeEdge(previous,target.key);var normalized=normalizeSlopeSegments();renderSlope();reportSlopeNormalization(normalized);}
function extendSlopeNode(key){var source=slopeNode(key);if(!source)return;var step={up:{x:0,y:-110},right:{x:155,y:0},down:{x:0,y:110},left:{x:-155,y:0}}[slope.direction],point={x:source.x+step.x,y:source.y+step.y};for(var attempt=0;attempt<5;attempt+=1){var occupied=slope.nodes.some(function(node){return Math.hypot(node.x-point.x,node.y-point.y)<70;});if(!occupied)break;point.x+=step.x;point.y+=step.y;}point.x=Math.max(55,Math.min(945,point.x));point.y=Math.max(40,Math.min(560,point.y));var target=createSlopeNode(point);createSlopeEdge(source.key,target.key);renderSlope();}
function connectSelectedSlopeNodes(){var ids=selectedNodeKeys();if(ids.length<2){studioState('slopeState','请按住 Shift 选择两个节点后再连接。','bad');return;}var created=createSlopeEdge(ids[0],ids[1]);renderSlope();studioState('slopeState',created.length?'已建立 '+created.length+' 个逐节点坡段。':'所选节点之间已有逐节点连线。',created.length?'ok':'');}
function orientSlopeNode(kind){var ids=selectedNodeKeys();if(ids.length!==1)return;var key=ids[0],changed=0;slope.edges.forEach(function(edge){if(kind==='high'&&edge.to===key){var from=edge.from;edge.from=edge.to;edge.to=from;changed+=1;}else if(kind==='low'&&edge.from===key){var origin=edge.from;edge.from=edge.to;edge.to=origin;changed+=1;}});slope.lastResults=null;renderSlope();studioState('slopeState',kind==='high'?'相邻坡段已从该高点向外排水。':'相邻坡段已汇入该低点。',changed?'ok':'');}
function autoSlope(){if(!window.SpecFlowRoadSlope){studioState('slopeState','坡度计算模块未加载。','bad');return;}if(!slope.nodes.some(function(node){return node.fixed&&node.elevation!==null&&Number.isFinite(Number(node.elevation));})){studioState('slopeState','请先为至少一个节点输入标高并设为控制标高。','bad');return;}slope.nodes.forEach(function(node){if(!node.fixed)node.elevation=null;});var result=window.SpecFlowRoadSlope.calculateNetwork({nodes:slope.nodes,edges:slope.edges,decimals:slopeDecimals()});Object.keys(result.elevations).forEach(function(key){var node=slopeNode(key);if(node)node.elevation=result.elevations[key];});slope.lastResults=result;renderSlope();var unresolved=slope.nodes.length-result.resolved,warnings=result.issues.length;studioState('slopeState',warnings?'网络已计算：'+result.resolved+'/'+result.total+' 个节点获得标高，发现 '+warnings+' 项冲突或规范提示。':'网络计算完成，全部坡段满足当前输入条件。',warnings||unresolved?'bad':'ok');}
function deleteSlopeSelection(){if(!slope.selected)return;if(slope.selected.type==='nodes'){var keys=new Set(slope.selected.ids||[]);slope.nodes=slope.nodes.filter(function(node){return!keys.has(node.key);});slope.edges=slope.edges.filter(function(edge){return!keys.has(edge.from)&&!keys.has(edge.to);});}else{slope.edges=slope.edges.filter(function(edge){return edge.id!==slope.selected.id;});}slope.selected={type:'nodes',ids:[]};slope.lastResults=null;renderSlope();}
function reverseSlopeEdge(){if(!slope.selected||slope.selected.type!=='edge')return;var edge=slopeEdge(slope.selected.id);if(!edge)return;var from=edge.from;edge.from=edge.to;edge.to=from;slope.lastResults=null;renderSlope();}
function exportSlope(){var payload=JSON.stringify({schemaVersion:3,unit:'m',layout:'illustrative-only',flowRule:'adjacent-nodes-only',nodes:slope.nodes,edges:slope.edges,calculation:slope.lastResults},null,2),blob=new Blob([payload],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='道路排水坡度网络.json';a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},1000);}
function resetSlope(){slope={nodes:[],edges:[],mode:'select',selected:{type:'nodes',ids:[]},drag:null,selectionBox:null,serial:1,edgeSerial:1,direction:'right',lastResults:null};setSlopeDirection('right');renderSlope();}

document.addEventListener('click',function(event){
  var target=event.target.closest&&event.target.closest('[data-studio-act]');if(!target)return;var action=target.getAttribute('data-studio-act');
  var monitorId=target.getAttribute('data-monitor-id');
  if(action==='chooseProjectBase')chooseProjectBase();else if(action==='createProject')createEngineeringProject();else if(action==='openProjectDirectory'&&workspaceState.current&&DESKTOP&&DESKTOP.projects)DESKTOP.projects.openDirectory(workspaceState.current.projectDirectory);else if(action==='syncProjectFolders')syncProjectFolders();else if(action==='addChecklistItem')addChecklistItem();else if(action==='saveWorkspaceSettings')saveWorkspaceSettings();else if(action==='chooseCalculator')chooseCalculator();else if(action==='saveCalculator')saveCalculator();else if(action==='launchCalculator')launchCalculator();else if(action==='openRoadSlope'){showPage('tools');document.getElementById('roadDesigner').scrollIntoView({behavior:'smooth'});}else if(action==='refreshBalance')refreshBalance();else if(action==='openSpecMonitors')openSpecMonitors();else if(action==='closeSpecMonitors')closeSpecMonitors();else if(action==='resetSpecMonitor')resetSpecMonitorForm();else if(action==='saveSpecMonitor')saveSpecMonitor();else if(action==='checkSpecMonitor')checkSpecMonitor(monitorId);else if(action==='checkAllSpecMonitors')checkAllSpecMonitors();else if(action==='editSpecMonitor')editSpecMonitor(monitorId);else if(action==='toggleSpecMonitor')toggleSpecMonitor(monitorId);else if(action==='deleteSpecMonitor')deleteSpecMonitor(monitorId);else if(action==='autoSlope')autoSlope();else if(action==='deleteSlope')deleteSlopeSelection();else if(action==='reverseSlopeEdge')reverseSlopeEdge();else if(action==='connectSlopeNodes')connectSelectedSlopeNodes();else if(action==='slopeNodeHigh')orientSlopeNode('high');else if(action==='slopeNodeLow')orientSlopeNode('low');else if(action==='exportSlope')exportSlope();else if(action==='clearSlope'){if(window.confirm('清空当前道路排水网络？'))resetSlope();}else if(action==='slopeMode')setSlopeMode(target.getAttribute('data-slope-mode'));else if(action==='slopeDirection')setSlopeDirection(target.getAttribute('data-direction'));
});
function applySlopeProperty(target,render){var prop=target.getAttribute&&target.getAttribute('data-slope-prop');if(!prop||!slope.selected)return false;if(slope.selected.type==='nodes'&&slope.selected.ids.length===1){var node=slopeNode(slope.selected.ids[0]);if(!node)return false;if(prop==='fixed')node.fixed=target.checked;else if(prop==='elevation'){node.elevation=target.value===''?null:Number(target.value);node.fixed=node.elevation!==null&&Number.isFinite(node.elevation);}else if(prop==='nodeLabel'){var label=String(target.value||'').trim();if(label&&!slope.nodes.some(function(item){return item.key!==node.key&&item.label===label;}))node.label=label;}}else if(slope.selected.type==='edge'){var edge=slopeEdge(slope.selected.id);if(!edge)return false;var map={edgeDistance:'distance',edgeSlope:'slope',edgeMinSlope:'minSlope',edgeMaxSlope:'maxSlope'},field=map[prop];if(field){edge[field]=target.value===''?'':Number(target.value);if(field==='distance')edge.needsDistance=target.value==='';}}slope.lastResults=null;if(render)renderSlope();else saveSlope();return true;}
document.addEventListener('change',function(event){
  if(event.target.id==='projectSelect'){openEngineeringProject(event.target.value);return;}
  var statusId=event.target.getAttribute&&event.target.getAttribute('data-check-status');if(statusId){updateChecklist(statusId,{status:event.target.value});return;}
  var noteId=event.target.getAttribute&&event.target.getAttribute('data-check-note');if(noteId){updateChecklist(noteId,{note:event.target.value});return;}
  applySlopeProperty(event.target,true);
});
document.addEventListener('input',function(event){
  applySlopeProperty(event.target,false);
});
document.addEventListener('keydown',function(event){if(event.ctrlKey&&event.altKey&&String(event.key).toLowerCase()==='c'){event.preventDefault();launchCalculator();}else if(event.ctrlKey&&event.altKey&&String(event.key).toLowerCase()==='r'){event.preventDefault();showPage('tools');document.getElementById('roadDesigner').scrollIntoView();}else if((event.key==='Delete'||event.key==='Backspace')&&document.querySelector('[data-workspace-page="tools"].active')&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement&&document.activeElement.tagName||'')){event.preventDefault();deleteSlopeSelection();}else if(event.key==='Escape'&&document.getElementById('specMonitorDialog').style.display!=='none'){event.preventDefault();event.stopImmediatePropagation();closeSpecMonitors();}});
var canvas=document.getElementById('slopeCanvas');
if(canvas){
  canvas.addEventListener('pointerdown',function(event){
    var nodeEl=event.target.closest&&event.target.closest('[data-slope-node]'),edgeEl=event.target.closest&&event.target.closest('[data-slope-edge]'),point=slopePoint(event);
    var activation=nodeEl?{type:'node',id:nodeEl.getAttribute('data-slope-node')}:edgeEl?{type:'edge',id:edgeEl.getAttribute('data-slope-edge')}:null,now=Date.now();
    if(activation&&slope.lastActivation&&activation.type===slope.lastActivation.type&&activation.id===slope.lastActivation.id&&now-slope.lastActivation.at<450){
      event.preventDefault();slope.drag=null;slope.lastActivation=null;
      if(nodeEl)extendSlopeNode(activation.id);
      else{slope.selected={type:'edge',id:activation.id};reverseSlopeEdge();}
      return;
    }
    slope.lastActivation=activation?{type:activation.type,id:activation.id,at:now}:null;
    if(nodeEl){var key=nodeEl.getAttribute('data-slope-node'),ids=selectedNodeKeys().slice();if(event.shiftKey){ids=ids.includes(key)?ids.filter(function(id){return id!==key;}):ids.concat(key);}else if(!ids.includes(key))ids=[key];slope.selected={type:'nodes',ids:ids};if(slope.mode==='select'&&ids.length){var origins={};ids.forEach(function(id){var node=slopeNode(id);origins[id]={x:node.x,y:node.y};});slope.drag={start:point,origins:origins};canvas.setPointerCapture(event.pointerId);}renderSlope();return;}
    if(edgeEl){slope.selected={type:'edge',id:edgeEl.getAttribute('data-slope-edge')};renderSlope();return;}
    if(slope.mode==='add'){addSlopeNode(point);return;}
    slope.selected={type:'nodes',ids:[]};slope.selectionBox={start:point,current:point};canvas.setPointerCapture(event.pointerId);renderSlope();
  });
  canvas.addEventListener('pointermove',function(event){var point=slopePoint(event);if(slope.drag){var dx=point.x-slope.drag.start.x,dy=point.y-slope.drag.start.y;Object.keys(slope.drag.origins).forEach(function(key){var node=slopeNode(key),origin=slope.drag.origins[key];if(node){node.x=Math.max(45,Math.min(955,origin.x+dx));node.y=Math.max(28,Math.min(572,origin.y+dy));}});renderSlope();}else if(slope.selectionBox){slope.selectionBox.current=point;renderSlope();}});
  canvas.addEventListener('pointerup',function(){var moved=Boolean(slope.drag);if(slope.selectionBox){var box=slope.selectionBox,left=Math.min(box.start.x,box.current.x),right=Math.max(box.start.x,box.current.x),top=Math.min(box.start.y,box.current.y),bottom=Math.max(box.start.y,box.current.y);slope.selected={type:'nodes',ids:slope.nodes.filter(function(node){return node.x>=left&&node.x<=right&&node.y>=top&&node.y<=bottom;}).map(function(node){return node.key;})};slope.selectionBox=null;}slope.drag=null;var normalized=moved?normalizeSlopeSegments():null;renderSlope();reportSlopeNormalization(normalized);});
}

loadEngineeringWorkspace();loadDesignTools();loadSpecMonitors();window.setInterval(loadSpecMonitors,60000);loadSlope();if(DESKTOP&&DESKTOP.balance)refreshBalance();
})();
